# LimboCaptcha - Captcha BEFORE LimboAuth
# Author: KondrMS

recaptcha:
  site-key: "YOUR_SITE_KEY"
  secret-key: "YOUR_SECRET_KEY"
  url-format: "https://captcha.fakeworld.pw/captcha.html?token=${token}"
  timeout-minutes: 5

webserver:
  port: 8080
  api-port: 8081

messages:
  captcha-message: "&eПройдите проверку:"
  success-message: "&aПроверка пройдена! Перемещаем на авторизацию..."
  kick-message: "&cВремя истекло!"
  fail-kick-message: "&cПроверка не пройдена!"
